#!/bin/bash

# Setup default configuration
# Generated by install.sh

echo "🔧 Setting up default configuration..."

# Wait for backend to be ready
echo "⏳ Waiting for backend to be ready..."
sleep 10

# Create database schema first
echo "🗄️  Creating database schema..."
docker exec restreamer-backend npx prisma db push

# Wait a moment for schema to be created
sleep 5

# Create default admin user
echo "👤 Creating default admin user..."
docker exec restreamer-backend node -e "
const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');

async function createAdmin() {
  const prisma = new PrismaClient();
  
  try {
    const hashedPassword = await bcrypt.hash('admin123', 12);
    
    await prisma.user.upsert({
      where: { email: 'admin@restreamer.website' },
      update: {},
      create: {
        id: 'admin-1',
        email: 'admin@restreamer.website',
        password: hashedPassword,
        name: 'Admin User',
        role: 'ADMIN'
      }
    });
    
    console.log('✅ Admin user created: admin@restreamer.website');
    console.log('🔑 Password: admin123');
  } catch (error) {
    console.error('❌ Error creating admin user:', error);
  } finally {
    await prisma.$disconnect();
  }
}

createAdmin();
"

echo "✅ Setup complete!"
